name: mediherb
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning for your app
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  shared_preferences: ^2.1.1
  http: ^1.2.2                # Add the HTTP package for API requests
  flutter_secure_storage: ^5.0.2  # Add secure storage for storing JWT tokens
  provider: ^6.0.5             # Optional: Use provider for state management, if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Define assets and fonts
  assets:
    - assets/icons/    
    - assets/images/        # Ensure this path is correct
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf

